#!/bin/bash

function connect_database() {
    echo -n "Enter database name to connect: "
    read db_name
    db_path="$DB_DIR/$db_name"

    if [ -d "$db_path" ]; then
        echo "$db_name" > .current_db
        echo "Connected to database: $db_name"
    else
        echo "Database '$db_name' does not exist!"
    fi
}

