#!/bin/bash
DB_DIR="./databases"

function create_database() {
    echo -n "Enter database name: "
    read db_name
    db_path="$DB_DIR/$db_name"
    if [ -d "$db_path" ]; then
        echo "Database '$db_name' already exists!"
    else
        mkdir "$db_path"
        echo "Database '$db_name' created successfully."
    fi
}

