#!/bin/bash
DB_DIR="./databases"

function create_table() {
    echo -n "Enter database name: "
    read db_name
    db_path="$DB_DIR/$db_name"

    if [ ! -d "$db_path" ]; then
        echo "Database '$db_name' does not exist!"
        return
    fi

    echo -n "Enter table name: "
    read table_name
    table_path="$db_path/$table_name.csv"
    
    if [ -f "$table_path" ]; then
        echo "Table '$table_name' already exists!"
    else
        echo -n "Enter column names (comma-separated): "
        read columns
        echo "$columns" > "$table_path"
        echo "Table '$table_name' created successfully."
    fi
}

