#!/bin/bash
DB_DIR="./databases"

function insert_data() {
    echo -n "Enter database name: "
    read db_name
    db_path="$DB_DIR/$db_name"

    if [ ! -d "$db_path" ]; then
        echo "Database '$db_name' does not exist!"
        return
    fi

    echo -n "Enter table name: "
    read table_name
    table_path="$db_path/$table_name.csv"

    if [ ! -f "$table_path" ]; then
        echo "Table '$table_name' does not exist!"
        return
    fi

    echo -n "Enter values (comma-separated): "
    read values
    echo "$values" >> "$table_path"
    echo "Data inserted successfully."
}

