#!/bin/bash
DB_DIR="./databases"

function list_tables() {
    echo -n "Enter database name: "
    read db_name
    db_path="$DB_DIR/$db_name"
    
    if [ -d "$db_path" ]; then
        echo "Tables in '$db_name':"
        ls "$db_path"
    else
        echo "Database '$db_name' does not exist!"
    fi
}

